### ISSUE TITLE
FSP To-Do List

### ISSUE THREAD

**Issue by mwmadsen67** [thedavidelrod/TimbreHaar#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the MVP List
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain superfluous routes
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by mwmadsen67** [comment]
Hey David, great work so far, here is my feedback on what's currently there:

**MVP-list**: Looks great, no issues here.
**Schema**: Everything is formatted nicely, and looks good, just have a couple questions. I am wondering with the user info, are you sure you want a unique username and a unique email? I know on soundcloud they have unique email and then a display name, which can be anything. Also do you want any other columns like bio or country? Also for sounds, what is the tag column for? 
**Sample State:** You should make sure that your sample state includes session and errors slice of state. Also, sounds should include `commentIds` with the ids of whatever comments there are for that sound. You can imagine navigating around the website, eventually there would be a bunch of comments in your state from different sounds. The commentIds array is what would tell you which comments to render.

**Comment by thedavidelrod** [comment]
Thanks for the feedback Mike. Looking forward to your guidance as TimbreHaar moves forward. I made the edits based on your suggestions and added the routes. Let me know what you think.

-DE

**Comment by mwmadsen67** [comment]
Looking at your routes now, some more notes:

**Backend Routes**:
- you will likely need a route for updating sounds
- theres some weird formatting going on on the post and delete sounds
- it is unnecessary to nest comments under sounds. For post requests, the sound_id will be included in the data anyways (think of what would be in comment_params). For delete requests, the only information needed is the id of the comment.

**Frontend Routes**: 
- You will have to make a login/sign up modal for your app, so these will not have their own frontend routes. Notice how on soundcloud that you can sign in from anywhere on the site since the button is on the navbar, and the url doesnt change when looking at the modal. Because of this I would list the sessionform component at the same level as the navbar

**Comment by mwmadsen67** [comment]
I forgot to mention for your sample state: 
- Users and sounds will both need to include a url for images. 
- Sounds should include an uploaderId and maybe something like uploaderName even. Think about all the info you want to grab from your backend when you're displaying sounds.
- All variable names should be in camelCase, since the state is on your javascript frontend.
